### ISSUE TITLE
[Bug] TrueNAS disconnects in HASS

### ISSUE THREAD

**Issue by KLServer** [tomaae/homeassistant-truenas#176] opened 2024-10-31 09:01 UTC
Hello

I freshly installed the new update on a new VM, I wanted to test somethings out before I made the switch from OMV to TrueNAS, I tried the integration, it connects but then immediately says "TrueNAS disconnected".

I run the newest version on both devices: 

HASS:
Core
2024.10.4
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.4

TrueNAS:
 ElectricEel-24.10.0

Thanks!

**Comment by sansgil** [comment] 2024-10-31 09:14
I'm also having this issue since updating TrueNAS to `ElectricEel-24.10.0`.

I get a number of errors showing in the HA OS logs.

```
This error originated from a custom integration.

Logger: custom_components.truenas.coordinator
Source: /usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:425
integration: TrueNAS (documentation, issues)
First occurred: 30 October 2024 at 16:44:54 (2 occurrences)
Last logged: 30 October 2024 at 17:03:07

Unexpected error fetching TrueNAS data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 96, in _async_update_data
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 427, in get_systemstats
    max(tmp_graph[i]["aggregations"]["mean"].values()), 2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

```
This error originated from a custom integration.

Logger: custom_components.truenas.coordinator
Source: /usr/src/homeassistant/homeassistant/helpers/update_coordinator.py:386
integration: TrueNAS (documentation, issues)
First occurred: 30 October 2024 at 17:01:04 (1 occurrences)
Last logged: 30 October 2024 at 17:01:04

Error fetching TrueNAS data: TrueNas Disconnected
```

**Comment by Poshy163** [comment] 2024-10-31 14:20
Dupe of #170

**Comment by KLServer** [comment] 2024-10-31 14:44
@Poshy163 yes, that solutions works! Thanks! 

@pascalsavigny fyi!

**Comment by AivarasAukselis** [comment] 2024-11-08 10:46
Thanks for fixing it @itsniawan! Would it be possible to tag the current master branch such that we could update with HACS?

**Comment by itsniawan** [comment] 2024-11-08 13:23
> Thanks for fixing it @itsniawan! Would it be possible to tag the current master branch such that we could update with HACS?

Here you go...
[TrueNAS v1.2.5.1](https://github.com/itsniawan/homeassistant-truenas/releases/tag/v1.2.5.1)

**Comment by AivarasAukselis** [comment] 2024-11-08 13:59
> > Thanks for fixing it @itsniawan! Would it be possible to tag the current master branch such that we could update with HACS?
> 
> Here you go... [TrueNAS v1.2.5.1](https://github.com/itsniawan/homeassistant-truenas/releases/tag/v1.2.5.1)

Oh, I thought you could tag on the upstream, not a fork. Nvmd...

**Comment by itsniawan** [comment] 2024-11-08 19:48
> > > Thanks for fixing it @itsniawan! Would it be possible to tag the current master branch such that we could update with HACS?
> > 
> > 
> > Here you go... [TrueNAS v1.2.5.1](https://github.com/itsniawan/homeassistant-truenas/releases/tag/v1.2.5.1)
> 
> Oh, I thought you could tag on the upstream, not a fork. Nvmd...

Sorry, i couldn't do that, i'm not part of the developer team.

**Closed** 2024-11-14 07:48 UTC
Labels: bug
