### ISSUE TITLE
[Bug] Invalid device info

### ISSUE THREAD

**Issue by firstof9** [tomaae/homeassistant-truenas#103] opened 2023-08-30 22:59 UTC
## Describe the issue

Home Assistant is reporting the following error when attempting to load the integration:
`2023-08-30 15:52:12.195 ERROR (MainThread) [homeassistant.components.binary_sensor] truenas: Not adding entity with invalid device info: ...`

## How to reproduce the issue

Install integration
Setup integration

## Expected behavior

No error messages

## Software versions

 - Home Assistant version: 2023.9.0b0 
 - TrueNAS integration version: 0.6.1 
 - TrueNAS version: TrueNAS-SCALE-22.12.2 

## Traceback/Error logs

```
2023-08-30 15:52:12.195 ERROR (MainThread) [homeassistant.components.binary_sensor] truenas: Not adding entity with invalid device info: Invalid device info [...] for 'truenas' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

**Comment by tomaae** [comment] 2023-08-31 00:36
known issue, caused by unlisted breaking change in last HA release. will be fixed in next integration release

**Comment by firstof9** [comment] 2023-08-31 01:15
Sweet thanks, figured I'd make an issue either way for any others who may hit this as well.

**Comment by firstof9** [comment] 2023-08-31 01:16
If you drop a beta, I'll be happy to test it out.

**Comment by tomaae** [comment] 2023-08-31 03:13
there wont be a beta for this integation.
I'm already working on new system for my integrations which is updated to latest HA standards. Once that is fully tested, I will just move it over to this integration and others since they share common code for this reason.

**Comment by firstof9** [comment] 2023-08-31 15:14
Either way, I'd be happy to test.

**Comment by Basserra** [comment] 2023-09-01 22:23
+1 Experiencing this issue for a while now too. Too lazy to post a report myself. Glad to hear it's known and in process. Thanks for the project/integration!

**Closed** 2023-09-18 08:49 UTC
Labels: bug, planned

**Comment by ruegr** [comment] 2023-11-07 08:52
Hi @tomaae,
unfortunately I still have the same problem. HomeAssistant, HACS and the TrueNAS integration are up to date (2023.11.1, 1.33.0, v.1.2.5). I removed and reinstalled the complete Integration and the device itself - but there ist just one entity visible (update.update).
After a fresh reboot the following truenas related logs are generated:

- Error while setting up truenas platform for sensor
  - `Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/truenas/sensor.py", line 31, in async_setup_entry
    await model_async_setup_entry(
  File "/config/custom_components/truenas/model.py", line 58, in model_async_setup_entry
    update_controller()
  File "/config/custom_components/truenas/model.py", line 44, in update_controller
    model_update_items(
  File "/config/custom_components/truenas/model.py", line 111, in model_update_items
    if tmp := _register_entity(sensors, item_id, uid, uid_sensor):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/model.py", line 78, in _register_entity
    _sensors[_item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 922, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 720, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity fastpool/iocage/jails/blender>`

- Error while setting up truenas platform for binary_sensor
  - `Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/truenas/binary_sensor.py", line 31, in async_setup_entry
    await model_async_setup_entry(
  File "/config/custom_components/truenas/model.py", line 58, in model_async_setup_entry
    update_controller()
  File "/config/custom_components/truenas/model.py", line 44, in update_controller
    model_update_items(
  File "/config/custom_components/truenas/model.py", line 111, in model_update_items
    if tmp := _register_entity(sensors, item_id, uid, uid_sensor):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/model.py", line 78, in _register_entity
    _sensors[_item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 922, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 720, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity None=off>`

If I can supply more information please dont hesitate to ask, I really appreciate your work!

**Comment by tomaae** [comment] 2023-11-07 09:58
thats not the same problem. open a new ticket for this one and provide debugs as well. there is most likely some error before those messages.
